const USER_REQUEST_RECEIVE = 'USER_REQUEST_RECEIVE';
const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';
const USER_UPDATE_DATA = 'USER_UPDATE_DATA';
const USER_DELETE_DATA = 'USER_DELETE_DATA';

export {
    USER_REQUEST_RECEIVE,
    USER_REQUEST_ERROR,
    USER_UPDATE_DATA,
    USER_DELETE_DATA
}