const USER_REQUEST_RECEIVE = 'USER_REQUEST_RECEIVE';
const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';
const USER_UPDATE_DATA = 'USER_UPDATE_DATA';
const USER_DELETE_DATA = 'USER_DELETE_DATA';

const GET_MESSAGES_RECEIVE = 'GET_MESSAGES_RECEIVE';
const UPLOAD_NEW_MESSAGES_RECEIVE = 'UPLOAD_NEW_MESSAGES_RECEIVE';
const PUSH_MESSAGE = 'PUSH_MESSAGE';
const BLOCK_UPLOAD_MESSAGES = 'BLOCK_UPLOAD_MESSAGES';

export {
    USER_REQUEST_RECEIVE,
    USER_REQUEST_ERROR,
    USER_UPDATE_DATA,
    USER_DELETE_DATA,

    GET_MESSAGES_RECEIVE,
    UPLOAD_NEW_MESSAGES_RECEIVE,
    PUSH_MESSAGE,
    BLOCK_UPLOAD_MESSAGES
}